### ISSUE TITLE
Fromming a From doesn't work

### ISSUE THREAD

**Issue by deregtd** [rgst-io/stencil#283]
I have three nested stencil modules:
* stencil-frontends, which references...
* stencil-service, which references...
* stencil-terraform

stencil-frontends' manifest has:
```
  manage-tf:
    from: github.com/udemy/stencil-service
 ```

stencil-service's manifest has:
```
  manage-tf:
    from: github.com/udemy/stencil-terraform
```

finally, stencil-terraform's manifest has:
```
  manage-tf:
    required: false
    default: false
    description: Boolean to enable terraform management
    schema:
      type: boolean
```

From a template in stencil-frontends, if I call `stencil.Arg "manage-tf"`, it errors like it can't find it:
```
ERRO failed to run error="failed to render template \"github.com/udemy/stencil-frontends/.github/workflows/build-and-publish.yml.tpl\": template: github.com/udemy/stencil-frontends/.github/workflows/build-and-publish.yml.tpl:21:86: executing \"github.com/udemy/stencil-frontends/.github/workflows/build-and-publish.yml.tpl\" at <\"manage-tf\">: invalid value; expected bool"
```

If i change the stencil-frontends reference away from nested-`from`ing stencil-service and instead directly `from` stencil-terraform, it works as expected.
