### ISSUE TITLE
stencil.Arg on a non-stencil.yaml-specified arg that's an optional 'object' errors

### ISSUE THREAD

**Issue by deregtd** [rgst-io/stencil#295]
When trying to add some encapsulation of related "argument sets", we ran into this issue.  Super simple repro:

manifest.yaml:
```
name: github.com/udemy/st
type: templates
arguments:
  test:
    required: false
    schema:
      type: object
```

stencil.yaml:
```
name: bob
arguments:
  dsdsfg: 4
modules:
  - name: github.com/udemy/st
replacements:
  github.com/udemy/st: ./
```

templates/t.tpl
```
{{- stencil.Debug (stencil.Arg "test") }}
```

When you run stencil, you get:
```
ERRO failed to run error="failed to render template \"github.com/udemy/st/t.tpl\": template: github.com/udemy/st/t.tpl:1:26: executing \"github.com/udemy/st/t.tpl\" at <stencil.Arg>: error calling Arg: data failed json schema validation (github.com/udemy/st/arguments/test): invalid jsonType map[interface {}]interface {}"
```

So somehow the default it's trying to unmarshal isn't nil/null, it's a `map[any]any`...
